language: python

# Install the apt prerequisites
addons:
  apt:
    packages:
      - python-pygments

# Clean and don't fail
install:
  # install latest release version
  - wget --debug --verbose https://github.com/gohugoio/hugo/releases/download/v0.48/hugo_0.48_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - rm -rf docs || exit 0

# Build the website
script:
  - hugo

# Deploy to GitHub pages
deploy:
  provider: pages  # GitHub Pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  verbose: true
  keep-history: true
  local_dir: docs # Deploy From Only One Folder
  target_branch: build  # branch contains blog content
  on:
    branch: master

after_deploy:
  - cd docs
  - git init
  - git add .
  - git commit -m "deploy"
  - git remote add -t master liveserver https://$GITHUB_TOKEN@github.com/CounterpartyXCPC/counterpartyxcpc.github.io.git
  - git pull liveserver
  - git push --set-upstream liveserver master --force
